configurations:

  GenerateTask:
    named: true
    properties:
      apiFile:
        type: RegularFileProperty
        includeInDefaults: false
        mandatory: true
      apiFragments:
        type: ConfigurableFileCollection
      externalReferenceResolution:
        type: ExternalReferencesResolutionOption
        default: targeted
      basePackage:
        type: CharSequence
        includeInDefaults: false
        mandatory: true
      outputDirectory:
        type: DirectoryProperty
        dataflow: Output
        default: ProjectLayout.buildDirectory.dir("generated/sources/fabrikt")
      sourcesPath:
        type: CharSequence
        default: src/main/kotlin
      resourcesPath:
        type: CharSequence
        default: src/main/resources
      validationLibrary:
        type: ValidationLibraryOption
        default: Jakarta
      quarkusReflectionConfig:
        type: Boolean
        default: false
      typeOverrides:
        type: TypeOverrides
      client:
        type: GenerateClient
      controller:
        type: GenerateController
      model:
        type: GenerateModel
      skip:
        type: Boolean
        default: false

  TypeOverrides:
    properties:
      datetime:
        type: DateTimeOverrideOption
        default: OffsetDateTime
      binary:
        type: BinaryOverrideOption
        default: ByteArray

  GenerateClient:
    properties:
      generate:
        type: Boolean
        default: false
      resilience4j:
        type: Boolean
        default: false
      suspendModifier:
        type: Boolean
        default: false
      springResponseEntityWrapper:
        type: Boolean
        default: false
      target:
        type: ClientTargetOption
        default: OkHttp

  GenerateController:
    properties:
      generate:
        type: Boolean
        default: false
      authentication:
        type: Boolean
        default: false
      suspendModifier:
        type: Boolean
        default: false
      completionStage:
        type: Boolean
        default: false
      target:
        type: ControllerTargetOption
        default: Spring

  GenerateModel:
    properties:
      generate:
        type: Boolean
        default: true
      extensibleEnums:
        type: Boolean
        default: false
      javaSerialization:
        type: Boolean
        default: false
      quarkusReflection:
        type: Boolean
        default: false
      micronautIntrospection:
        type: Boolean
        default: false
      micronautReflection:
        type: Boolean
        default: false
      includeCompanionObject:
        type: Boolean
        default: false
      sealedInterfacesForOneOf:
        type: Boolean
        default: false
      nonNullMapValues:
        type: Boolean
        default: false
      ignoreUnknownProperties:
        type: Boolean
        default: false
      suffix:
        type: CharSequence
        default: null
      serializationLibrary:
        type: SerializationLibraryOption
        default: Jackson

options:

  ExternalReferencesResolutionOption:
    source: com.cjbooms.fabrikt.cli.ExternalReferencesResolutionMode
    mapping:
      targeted: TARGETED
      aggressive: AGGRESSIVE

  DateTimeOverrideOption:
    source: com.cjbooms.fabrikt.cli.CodeGenTypeOverride
    mapping:
      OffsetDateTime: null
      Instant: DATETIME_AS_INSTANT
      LocalDateTime: DATETIME_AS_LOCALDATETIME

  BinaryOverrideOption:
    source: com.cjbooms.fabrikt.cli.CodeGenTypeOverride
    mapping:
      ByteArray: null
      InputStream: BYTEARRAY_AS_INPUTSTREAM

  ValidationLibraryOption:
    source: com.cjbooms.fabrikt.cli.ValidationLibrary
    mapping:
      Jakarta: JAKARTA_VALIDATION
      Javax: JAVAX_VALIDATION
      NoValidation: NO_VALIDATION

  ClientTargetOption:
    source: com.cjbooms.fabrikt.cli.ClientCodeGenTargetType
    mapping:
      OkHttp: OK_HTTP
      OpenFeign: OPEN_FEIGN

  ControllerTargetOption:
    source: com.cjbooms.fabrikt.cli.ControllerCodeGenTargetType
    mapping:
      Spring: SPRING
      Micronaut: MICRONAUT
      Ktor: KTOR

  SerializationLibraryOption:
    source: com.cjbooms.fabrikt.cli.SerializationLibrary
    mapping:
      Jackson: JACKSON
      Kotlin: KOTLINX_SERIALIZATION
