name: Update Fabrikt README

on:
  push:
    tags:
      - 'test/**'

jobs:

  update-fabrikt-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout acanda/fabrikt
        uses: actions/checkout@v4
        with:
          repository: acanda/fabrikt
          path: acanda-fabrikt

      - name: Checkout acanda/fabrikt-gradle-plugin
        uses: actions/checkout@v4
        with:
          repository: acanda/fabrikt-gradle-plugin
          path: acanda-fabrikt-gradle-plugin

      - name: Extract release and Fabrikt versions
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/test/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Release version: $RELEASE_VERSION"
          FABRIKT_VERSION=$(grep -oP 'fabrikt = \{ group = "com.cjbooms", name = "fabrikt", version = "\K[^"]+' acanda-fabrikt-gradle-plugin/gradle/libs.versions.toml)
          echo "FABRIKT_VERSION=$FABRIKT_VERSION" >> $GITHUB_ENV
          echo "Extracted Fabrikt version: $FABRIKT_VERSION"
